require 'plist'
require_relative './sublime_syntax_convertor/version'
require_relative './sublime_syntax_convertor/formatter'
require_relative './sublime_syntax_convertor/patterns'
require_relative './sublime_syntax_convertor/syntax_yaml'
require_relative './sublime_syntax_convertor/convertor'
